### ISSUE TITLE
Cannot init

### ISSUE THREAD

**Issue by clebio** [kekwork/terraform-provider-ip#1] opened 2021-06-15 19:55 UTC
Hey, sweet little project! I just gave it a spin, but unfortunately cannot get `terraform init` to run:

```sh
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of kekwork/ip...
- Installing kekwork/ip v0.0.1...
╷
│ Error: Failed to install provider
│
│ Error while installing kekwork/ip v0.0.1: zip: not a valid zip file
╵
```

## Repro

```sh
mkdir repro; cd repro

cat > ip.tf <<EOF
terraform {
  required_version = "~> 1.0"

  required_providers {
    ip = {
      source = "registry.terraform.io/kekwork/ip"
    }
  }
}

provider "ip" {}
data "ip_v4" "home" {}

output "home_ip" {
    value = data.ip_v4.home.ip
}
EOF

terraform init
```

My env:
```
$ terraform version
Terraform v1.0.0
on darwin_amd64
```

You might also consider updating the provider doc page (https://registry.terraform.io/providers/kekwork/ip/latest/docs), since a non-hashicorp source requires:
```
terraform {
  required_providers {
    ip = {
      source = "registry.terraform.io/kekwork/ip"
   }
}
```
Otherwise, we get this error on init (granted, this is just standard 3rd-party provider stuff):
```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ip:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ip
```

**Comment by watts1t** [comment] 2021-06-30 15:34
Hi, I get the same problem, still trying to work out how to recreate this provider locally to see if I can fix it.

**Comment by watts1t** [comment] 2021-06-30 15:58
Seems like the problem is with the .goreleaser.yml file creating the zip file along with a tar.gz file so the terraform installation routine tries to unzip a tar.gz file which fails.  I have modified the file leaving just the zip creation and generated a pull request to merge in my changes...hopefully that fixes the problem!

Issue was found here: [fixed by removing any other archive formats](https://github.com/louy/terraform-provider-uptimerobot/commit/4f85ea9dd41176a999248164372a1aa19ec7b7cb)

**Comment by harshavmb** [comment] 2022-07-27 20:58
Hi @clebio @watts1t ,

If you are still interested in fetching the ip with terraform provider, please have a look at [ip](https://registry.terraform.io/providers/harshavmb/ip/1.0.0) provider.

At the moment, it fetches the local eth interface IPs. Shall there be a need to fetch NATed public IP, I can add.

Looking forward to hearing from you.

**Comment by clebio** [comment] 2022-07-27 21:20
hi @harshavmb , I don't currently have a need for this provider. I'd say NAT'd public IP sounds like a good feature to support , but I'm ok with closing this issue if the init is resolved (I have not yet tried to verify that). Thanks for following up all the same!

**Comment by harshavmb** [comment] 2022-07-28 06:22
Hi @clebio ,

Thanks for responding. The ip provider I shared isn't part of this repo. It's a different one. It's https://github.com/harshavmb/terraform-provider-ip

I'll add the public IP data source as well.

**Comment by KeisukeYamashita** [comment] 2023-06-23 04:06
I'm so sorry about the late reply, I will update everything until the end of this month 🙏

**Comment by KeisukeYamashita** [comment] 2023-06-23 13:23
Thank you very much!

The new version `0.0.2` will have no issue 🙏 

```console
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding kekwork/ip versions matching "0.0.2"...
- Installing kekwork/ip v0.0.2...
- Installed kekwork/ip v0.0.2 (self-signed, key ID 15A08EEB40AA38BA)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

> You might also consider updating the provider doc page (https://registry.terraform.io/providers/kekwork/ip/latest/docs), since a non-hashicorp source requires:

The installation configuration will be suggested on Terraform Registry like below:

<img width="1412" alt="image" src="https://github.com/kekwork/terraform-provider-ip/assets/23056537/cedb8e9a-cbd8-4f33-8b76-e2c45be6c8b7">

**Closed as completed** 2023-06-23 13:23 UTC
